project:
  type: book

book:
  title: "Data Visualization with R and ggplot"
  author: "Jan Zilinsky"
  date: ""
  chapters:
    - index.qmd
    - 1_principles.qmd
    - 2_toplines-and-cross-tabs.qmd
    - 3_B_timeseries.qmd
    - 3_C_financial-markets.qmd
    - 3_standard-charts.qmd
    - 4a_tweet_ratings.qmd
    - 4b_heatmaps-ridgelines.qmd
    - 4c_advanced-ggplot.qmd
    - 5_visualizing-models.qmd
    - part: "Resources"
      chapters:
        - typology.qmd
        - datasets.qmd
        - references.qmd
    - part: "Appendix"
      chapters:
        - tidyverse-refresher.qmd
        - r-snippets-appendix.qmd
        - class-exercises.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
  pdf:
    documentclass: scrreprt
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    colorlinks: true
    keep-tex: false
    code-block-bg: false
    # Code folding doesn't work in PDF, so code is always visible
    # This is usually desirable for printed material

execute:
  message: FALSE
  warning: FALSE

editor: source