project:
  type: book

book:
  title: "Data Visualization with R and ggplot"
  author: "Jan Zilinsky"
  date: ""
  chapters:
    - index.qmd
    - 1_principles.qmd
    - 2_toplines-and-cross-tabs.qmd
    - 3_B_timeseries.qmd
    - 3_standard-charts.qmd
    - 4_advanced-ggplot.qmd
    - 4b_tweet_ratings.qmd
    - 5_visualizing-models.qmd
    - part: "Resources"
      chapters:
        - typology.qmd
        - datasets.qmd
        - references.qmd
    - part: "Appendix"
      chapters:
        - tidyverse-refresher.qmd
        - class-exercizes.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
execute:
  message: FALSE
  warning: FALSE
  pdf:
    documentclass: scrreprt

editor: visual
