project:
  type: book

book:
  title: "Telling stories with R: Data Visualization"
  author: "Jan Zilinsky"
  date: ""
  chapters:
    - index.qmd
    - 1_principles.qmd
    - 2_toplines-and-cross-tabs.qmd
    - 3_standard-charts.qmd
    - 4_advanced-ggplot.qmd
    - 5_visualizing-models.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

