project:
  type: book

book:
  title: "Data Visualization with R and ggplot"
  author: "Jan Zilinsky"
  date: ""
  chapters:
    - index.qmd
    - 1_principles.qmd
    - typology.qmd
    - 2_toplines-and-cross-tabs.qmd
    - 3_B_timeseries.qmd
    - 3_standard-charts.qmd
    - 4_advanced-ggplot.qmd
    - 5_visualizing-models.qmd
    - datasets.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
execute:
  message: FALSE
  warning: FALSE
  pdf:
    documentclass: scrreprt

editor: visual
