# Datasets {.unnumbered}

## Included with course materials:

-   [Nationscape surveys](https://github.com/zilinskyjan/DataViz/tree/main/data_nationscape2019) (first 10 waves)
-   [Spending, debt, and fiscal deficits](https://github.com/zilinskyjan/DataViz/blob/main/data_macro/imf-fiscalmonitor-apr2023.csv) (IMF Fiscal Monitor, Apr. 2023)
-   [Inflation data](https://github.com/zilinskyjan/DataViz/blob/main/data_macro/inflation_WDI.csv) (WDI)
- [Health-adjusted life expectancy](https://github.com/zilinskyjan/DataViz/blob/main/data/health_adjusted_life_expectancy_2019.csv) (HALE, 2019). Global Burden of Disease Study. Institute for Health Metrics and Evaluation (IHME).
-   [COVID severity](https://github.com/zilinskyjan/DataViz/blob/main/data_macro/daily-covid-cases-deaths.csv) (daily data).
-   [Surveys about conspiracy thinking and populism](https://github.com/zilinskyjan/DataViz/tree/main/data_AJPS2021) (Uscinski et al. 2021 [dataverse files](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/YFPQJH), [codebooks and question wording](https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2Fajps.12616&file=ajps12616-sup-0001-SuppMat.pdf))
-   [Articles about the economy](https://github.com/zilinskyjan/DataViz/blob/main/data/guardian_economy_articlesInPrint_2019_2023.rds) from The Guardian (obtained via the free API).
-   A dataset of [political science article abstracts](https://github.com/zilinskyjan/DataViz/blob/main/data/epsa2023.rds) for practicing descriptive text analysis (credit: [Benjamin Guinaudeau](https://github.com/benjaminguinaudeau/epsa2023/tree/main/data)).

### Utilities

-   [OECD country codes](https://github.com/zilinskyjan/DataViz/blob/main/data_macro/oced_codes.csv)

## Selected public datasets (potential options for students' projects)

[legislatoR: Interface to the Comparative Legislators Database](https://github.com/saschagobel/legislatoR)

[ParlEE plenary speeches V3 data set: Annotated full-text of 10 million sentence-level plenary speeches of six EU legislative chambers](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IETNNB)

[Social & Moral Psychology of COVID-19](https://osf.io/tfsza/?fbclid=IwAR20dU3oRzNvsgWIT-xzMX13JXrOhcOcffDrCXmbCc_lKiL8YMeLNsq4aWQ)

[Eurobarometer](https://t.co/fUaZvdsLnW): A harmonized dataset

[European Values Study](https://www.gesis.org/en/services/finding-and-accessing-data/european-values-study)

[MediaCloud](https://mediacloud.org)

[useNews](https://osf.io/uzca3/): Document-feature matrices of news articles (2019-20)

[CC-News](https://huggingface.co/datasets/cc_news): 708,241 English language news articles published between Jan 2017 and December 2019.

[Cumulative CES Common Content](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/II2DB6)

[CCES2020 - NYU module](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/6RQ4GX) (includes questions on social media use, political behaviors and personality traits).
