---
title: "Financial markets"
format: revealjs
execute:
  echo: true
---

##

```{r}
library(tidyverse)
library(tidyquant)

# Get stocks prices
stocks <- tq_get(c("NVDA", "AVGO","^GSPC"),
                 from = "2022-01-01",
                 to = "2025-02-07")

stocks

#write_csv(stocks,"data/stocks2022-25.csv")
```

##

This is not informative (we can only see what's going on for one the series)

```{r}
stocks %>%
 ggplot(aes(x = date, y = adjusted, color = symbol)) +
 geom_line() +
 theme_minimal() +
 labs(title = "NVIDIA vs Broadcom Stock Prices",
      y = "Adjusted Price",
      color = "Stock")
```



##

Not much better.

Do we really care about price? Price movements - returns and losses - are probably more important to most investors.

```{r}
stocks %>%
 ggplot(aes(x = date, y = adjusted, color = symbol)) +
 geom_line() +
 facet_grid( ~ symbol)
```

##

```{r}
stocks %>%
 ggplot(aes(x = date, y = adjusted, color = symbol)) +
 geom_line() +
 facet_wrap( ~ symbol,scales="free_y")
```

 

##

```{r}


# Calculate returns
returns <- stocks %>%
 group_by(symbol) %>%
 tq_transmute(select = adjusted,
              mutate_fun = periodReturn,
              period = "daily",
              col_rename = "ret") %>%
 ungroup() %>%
 pivot_wider(names_from = symbol,
             values_from = ret) %>%
 na.omit()

# Calculate rolling correlation
returns$roll_cor <- zoo::rollapply(data = returns[, c("NVDA", "AVGO")],
                              width = 30,
                              FUN = function(x) cor(x[,1], x[,2]),
                              by.column = FALSE,
                              align = "right",
                              fill = NA)

returns$roll_corNVSP <- zoo::rollapply(data = returns[, c("NVDA", "^GSPC")],
                                   width = 60,
                                   FUN = function(x) cor(x[,1], x[,2]),
                                   by.column = FALSE,
                                   align = "right",
                                   fill = NA)

```

## 30-Day Rolling Correlation of Daily Returns: NVIDIA vs Broadcom

```{r}
returns %>%
 filter(date >= "2022-04-01") %>%
 ggplot(aes(x = date, y = roll_cor)) +
 geom_line()
```

##

```{r}
returns %>%
 filter(date >= "2022-04-01") %>%
ggplot(aes(x = date, y = roll_cor)) +
 geom_line(color = "blue") +
 geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
 theme_minimal() +
 labs(subtitle = "30-Day Rolling Correlation of Daily Returns: NVIDIA vs Broadcom", title = "Do semiconductor industry giants move together?", y = "Correlation Coefficient", x = "Date") + scale_y_continuous(limits = c(-.5, 1))
```

##

```{r}
returns %>%
 filter(date >= "2022-04-01") %>%
 ggplot(aes(x = date, y = roll_corNVSP)) +
 geom_line(color = "blue") +
 geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
 theme_minimal() + labs(subtitle = "60-Day Rolling Correlation of Daily Returns: NVIDIA vs SP500",
      title = "Do semiconductor industry giants move together?",y = "Correlation Coefficient",x = "Date") +
 scale_y_continuous(limits = c(-.5, 1))
```

##

```{r}
# Scatter of returns
ggplot(returns, aes(x = NVDA, y = AVGO)) +
 geom_point() +
 geom_smooth(method = "lm") +
 labs(title = "Scatterplot of Daily Returns",
      x = "NVIDIA",
      y = "Broadcom") +
 geom_abline(intercept = 0, slope = 1, 
             color = "red3",linetype=2,linewidth=1) 
```


##

```{r}
ggplot(returns, aes(x = `^GSPC`, y = NVDA)) +
 geom_point() +
 labs(title = "Scatterplot of Daily Returns",
      x = "S&P500",
      y = "NVIDIA")
```

## Let's also look at correlation during different market conditions
```{r}

returns %>%
 mutate(year = year(date)) %>%
 group_by(year) %>%
 summarize(correlation = cor(NVDA, AVGO)) %>%
 print()
```

##

```{r}
returns %>% mutate(ym = floor_date(date,"month")) %>%
 group_by(ym) %>%
 summarize(correlation = cor(NVDA, `^GSPC`)) %>%
 ggplot(aes(x = ym, y = correlation)) +
 geom_col()
```

