---
title: "AI in education"
subtitle: "(Especially in this class)"
author: "Jan Zilinsky, TUM, January 2026"
format: 
  revealjs:
    slide-number: c
    theme: default
    css: intro-ai-teaching.css
---

# What should we do about AI?

# Main suggestion: We should have frank conversations

## What I think we shold not do

- Pretend chatbots don't exist
- Ban technology that you will probably use in your future workplace

## LLMs can be excellent teachers

-   **They "know" a lot.** [Loosely speaking]{.note}
-   **They are patient.** ["Let's go back", "explain it differently..."]{.note}
- **Explanations are adjustable.** [You can ask for a simpler or more advanced explanation at any time.]{.note}

------------------------------------------------------------------------

## AI tools can be excellent teachers

-   **They are multimodal.**
-   **You can speak and explain what exactly you know and where you get lost.**

------------------------------------------------------------------------


## Open questions {.spaced}

::: {.incremental}
- Can they spark curiosity?
- Or will they...
  - Encourage users to delegate too much?
  - Create uniformity in taste?
:::

::: fragment
*(Probably depends on the context, the user's personality, etc.)*
:::

------------------------------------------------------------------------

---

## Risks

-   **A perfectly frictionless intellectual environment could stunt your growth.**
-   **It could systematically shield you from genuinely uncomfortable ideas.**
-   **Memory features might prevent serendipitous discovery.** [Less of a risk when starting fresh conversations]{.note}

------------------------------------------------------------------------

## The freedom–laziness conundrum

- I want you to have every tutor, assistant, and explainer at your fingertips (AI included).

- That freedom to coast is a non-trivial temptation
    1. There is a difference between getting assistnace
    2. vs. vibe-coding, vibe-writing, vibe-analyzing...

**Please refrain from #2.** 

## We often mix up AI risks

### Brief reflections on (AI-driven) echo chambers

-   **The status quo is already flawed.** [People actively curate their own reality every day; plagiarism is nothing new...]{.note}
-   **Seeking comfort and looking to make your life easier...** [I don't see them as moral failings. They are fundamental aspects of human psychology]{.note}

::: fragment
*Given this reality, why should we see the AI version of non-ideal behaviors as uniquely dangerous?*
:::


------------------------------------------------------------------------

## Provisional takeaways

::: {.incremental .highlight-last}
-   AI tools can probably accelerate some forms of learning
-   But be mindful of the risks
-   This class is an opportunity to learn, get to know your classmates, build relationships, ...
-   Trade-offs are everywhere. Let me know how you think about them.[We should have open conversations about this.]{.note}
:::